version: "3.3"

services:
      server:
       depends_on: 
         - redis
       build: ./server
       networks:
         - webnet
       environment:
         - PORT=2999
       ports:
         - 3001-3005:2999
       deploy:
         resources:
           limits:
             cpus: '.05'

      redis:
       build: ./redis
       networks:
         - webnet
       container_name: redis

networks:
  webnet:
