version: "3.3"

services:
      server1:
       depends_on: 
         - redis
       build: ./server 
       networks:
         - webnet
       environment:
         - PORT=3001
       deploy:
         resources:
           limits:
             cpus: '.05'
       container_name: factServer1

      server2:
       depends_on: 
         - redis
       build: ./server
       networks:
         - webnet
       environment:
         - PORT=3002
       deploy:
         resources:
           limits:
             cpus: '.05'
       container_name: factServer2

      server3:
       depends_on: 
         - redis
       build: ./server
       networks:
         - webnet
       environment:
         - PORT=3003
       deploy:
         resources:
           limits:
             cpus: '.05'
       container_name: factServer3

      loadbalancer:
       depends_on: 
         - redis
         - server1
         - server2
         - server3
       build: ./balancer
       environment:
         - PORT=3000
       networks:
         - webnet       
       container_name: balancer
      

      redis:
       build: ./redis
       networks:
         - webnet
       container_name: redis

networks:
  webnet:
