version: "3"

services:
      server1:
       depends_on: 
         - redis
       build: ./server 
       networks:
         - webnet
       environment:
         - PORT=3001
       container_name: factServer1

      server2:
       depends_on: 
         - redis
       build: ./server
       networks:
         - webnet
       environment:
         - PORT=3002
       container_name: factServer2

      server3:
       depends_on: 
         - redis
       build: ./server
       networks:
         - webnet
       environment:
         - PORT=3003
       container_name: factServer3

      loadbalancer:
       depends_on: 
         - redis
       build: ./balancer
       networks:
         - webnet       
       container_name: balancer
      

      redis:
       build: ./redis
       networks:
         - webnet
       container_name: redis

networks:
  webnet:
